#!/bin/bash

# Example for runnning the C-ESM-EP test suite, using a clone
# of repository cesmep_test 
# We assume current script is at the root of such a cesmep_test dir
root=$(cd $(dirname $0); pwd)
# This script is currently tuned to machine spirit
# You have to check each parameter set below

# Set CliMAF environment
module use --append /net/nfs/tools/Users/SU/modulefiles/jservon
module load climaf/env20230611_climafV3.0_IPSL9
# For dev purpose, one may change the CLiMAF version used
# export CLIMAF=~/climaf_installs/climaf_running

# Must provide a cache which is not the same as for the reference comparison
export CESMEP_CLIMAF_CACHE=/scratchu/ssenesi/cesmep_climaf_caches/check

# For detailed log, set setx to 1
export setx=1
export mail=senesi@posteo.net

export CESMEP=$root/C-ESM-EP
$root/check_ref_comparison.sh reference_comparison reference_results $mail

#$root/compare_results.sh reference_comparison $root/reference_results test_comparison
